### ISSUE TITLE
ブランチの保護設定

### ISSUE THREAD

**Issue by taishi-matsumura** [human-osaka-game-2020/ActionGame_ono#4]
Settingsから、mainブランチの保護設定を行ってください。
最低、下記にはチェックを付けてください。
* コードレビューを通過したもの以外はmainブランチへmergeできないようにする
* mergeコミットを作らないようにする
* 管理者も対象にする

**Comment by ono-hikaru81** [comment]
設定しなおしました。

**Comment by taishi-matsumura** [comment]
問題無さそうですね。
現在の設定で都合が悪くなった際はまた変更しましょう。
