### ISSUE TITLE
環境構築手順を記載する

### ISSUE THREAD

**Issue by taishi-matsumura** [human-osaka-game-2020/ActionGame_ono#5]
~ソリューションファイルが存在しないため、ビルドできません。~
また、DXライブラリを用いた開発とのことですので、そちらも必要となりますね。
DXライブラリ自体は、リポジトリに入れずに公式サイトからDLさせるようにしても問題ありません。
その場合はREADMEに環境構築手順を記載してください。

**Comment by ono-hikaru81** [comment]
同階層内にあるはずなので探してみてください。

**Comment by taishi-matsumura** [comment]
> 同階層内にあるはずなので探してみてください。

ソリューションディレクトリの下にプロジェクトディレクトリを作成するのが一般的なので、プロジェクトファイルと同階層には存在しないと思い込み、見落としていました。
お手数をお掛けしてすみませんでした🙇🏻‍♂️

READMEの記載の方だけ進めてください。
